//NOTA : EL CODIGO QUE ESTA ENTRE LAS LINEAS 360 Y 364 LAS PUSE PARA DEMOSTRAR QUE SI YO IGUALO UNA
//VARIABLE A UN ELEMENTO HTML Y LO LUEGO IGUALO ESA VARIABLE A UNA SEGUNDA VARIABLE , SI YO DESPUES
//CON EL METODO STYLE INTENTO HACER UNA MODIFICACION A LA SEGUNDA VARIABLE DICHA MODIFICACION VA A
//AFECTAR TAMBIEN A LA PRIMERA VARIABLE . EN ESTE CASO LA MODIFICACION QUE APLIQUE SOBRE LA VARIABLE 
//TROLO TAMBIEN VA A AFECTAR A LA VARIABLE PUTO Y AL ELEMENTO DEL DOOM SOBRE LA CUAL ESTA IGUALADA
//var puto = document.querySelector(".enunciado")
//var trolo = puto
//trolo.addEventListener("click" , ()=>{
//trolo.style.display = "none"
//})






var datos = {
nombre : "martin",
apellido : "guardeño",
id : 44972416 
}

var titulo = document.querySelector(".titulo")


